# Generated by Django 5.2.17 on 2026-08-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0002_contact_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('basket', 'Корзина'), ('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменён')], db_index=True, default='basket', max_length=9, verbose_name='Состояние')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Момент перехода basket -> new; у корзины не задан.', null=True, verbose_name='Оформлен')),
                ('delivery_last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия получателя')),
                ('delivery_first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя получателя')),
                ('delivery_middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество получателя')),
                ('delivery_email', models.EmailField(blank=True, max_length=254, verbose_name='Email получателя')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон получателя')),
                ('delivery_city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('delivery_street', models.CharField(blank=True, max_length=100, verbose_name='Улица')),
                ('delivery_house', models.CharField(blank=True, max_length=15, verbose_name='Дом')),
                ('delivery_structure', models.CharField(blank=True, max_length=15, verbose_name='Корпус')),
                ('delivery_building', models.CharField(blank=True, max_length=15, verbose_name='Строение')),
                ('delivery_apartment', models.CharField(blank=True, max_length=15, verbose_name='Квартира')),
                ('contact', models.ForeignKey(blank=True, help_text='Только трассируемость: получатель и адрес оформленного заказа читаются из полей delivery_* (ADR-024).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.contact', verbose_name='Контакт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-confirmed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product_name', models.CharField(blank=True, max_length=80, verbose_name='Товар')),
                ('shop_name', models.CharField(blank=True, max_length=50, verbose_name='Магазин')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('price_rrc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Рекомендуемая розничная цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productinfo', verbose_name='Предложение поставщика')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'basket')), fields=('user',), name='unique_basket_per_user'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['basket', 'new', 'confirmed', 'assembled', 'sent', 'delivered', 'canceled'])), name='order_state_is_known'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product_info'), name='unique_order_item_product_info'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_is_positive'),
        ),
    ]
