# Generated by Django 5.2.17 on 2026-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Реквизит доставки. Письма сервиса отправляются на email учётной записи и только на него (ADR-027).', max_length=254, verbose_name='Email получателя'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия получателя'),
        ),
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество получателя'),
        ),
    ]
