# Generated by Django 5.1.15 on 2026-08-30 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='Источник')),
                ('task_id', models.CharField(blank=True, max_length=64, verbose_name='Идентификатор задачи')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=7, verbose_name='Состояние')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Число обращений воркера к задаче, включая повторы.', verbose_name='Попыток выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Поставлен в очередь')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало выполнения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('offers_total', models.PositiveIntegerField(default=0, verbose_name='Позиций в прайсе')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='Создано предложений')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено предложений')),
                ('reactivated', models.PositiveIntegerField(default=0, verbose_name='Реактивировано')),
                ('deactivated', models.PositiveIntegerField(default=0, verbose_name='Деактивировано')),
                ('products_created', models.PositiveIntegerField(default=0, verbose_name='Создано товаров')),
                ('categories_linked', models.PositiveIntegerField(default=0, verbose_name='Категорий в прайсе')),
                ('error_code', models.CharField(blank=True, choices=[('insecure_source', 'Недопустимый источник'), ('file_too_large', 'Файл слишком большой'), ('source_unavailable', 'Источник недоступен'), ('download_error', 'Ошибка загрузки'), ('parse_error', 'Ошибка разбора прайса'), ('invalid_price_data', 'Прайс не прошёл проверку'), ('shop_not_found', 'Магазин не найден'), ('shop_metadata_mismatch', 'Прайс чужого магазина'), ('internal_error', 'Внутренняя ошибка')], max_length=32, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Пустое значение — запуск не человеком (поставщик, команда).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_logs', to='suppliers.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Запуск импорта',
                'verbose_name_plural': 'Запуски импорта',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['shop', '-created_at'], name='suppliers_importlog_shop_idx')],
            },
        ),
    ]
