# Generated by Django 5.1.15 on 2026-08-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='error_code',
            field=models.CharField(blank=True, choices=[('insecure_source', 'Недопустимый источник'), ('file_too_large', 'Файл слишком большой'), ('source_unavailable', 'Источник недоступен'), ('download_error', 'Ошибка загрузки'), ('parse_error', 'Ошибка разбора прайса'), ('invalid_price_data', 'Прайс не прошёл проверку'), ('shop_not_found', 'Магазин не найден'), ('shop_metadata_mismatch', 'Прайс чужого магазина'), ('retries_exhausted', 'Повторы исчерпаны'), ('internal_error', 'Внутренняя ошибка')], max_length=32, verbose_name='Код ошибки'),
        ),
    ]
